packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  better-sqlite3: true
  browser-tabs-lock: true
  esbuild: true
  msgpackr-extract: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - react-native-mmkv
  - react-native-nitro-modules

minimumReleaseAgeExclude:
  - expo-dev-client@57.0.9
  - expo-dev-launcher@57.0.9
  - expo-dev-menu@57.0.9

onlyBuiltDependencies:
  - better-sqlite3
  - browser-tabs-lock
  - esbuild
  - msgpackr-extract
  - unrs-resolver
