packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  better-sqlite3: true
  browser-tabs-lock: true
  esbuild: true
  msgpackr-extract: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - react-native-mmkv
  - react-native-nitro-modules

minimumReleaseAgeExclude:
  - expo-dev-client@57.0.9
  - expo-dev-launcher@57.0.9
  - expo-dev-menu@57.0.9
  - '@expo/cli@57.0.13'
  - '@expo/config-plugins@57.0.7'
  - babel-preset-expo@57.0.6
  - expo-asset@57.0.9
  - expo-file-system@57.0.2
  - expo-modules-core@57.0.10
  - expo@57.0.11
  - expo-build-properties@57.0.9
  - expo-router@57.0.11
  - expo-sharing@57.0.10
  - expo-symbols@57.0.2

onlyBuiltDependencies:
  - better-sqlite3
  - browser-tabs-lock
  - esbuild
  - msgpackr-extract
  - unrs-resolver
