version: '3.8'

services:

  traefik:
    ports:
      - 3306:3306
    volumes:
      # Traefik dynamic configuration
      - .docker/dev/dynamic.yml:/etc/traefik/dynamic.yml:ro
      # Development certificats
      - .docker/certs:/etc/certs:ro
    environment:
      - TRAEFIK_ENTRYPOINTS_MYSQL_ADDRESS=:3306
    # labels:
    #   - "traefik.http.routers.traefik-router.rule=Host(`traefik.$DOMAIN`, `localhost`)"

  # mariadb:

  api:
    image: holefeeder_api
    build:
      context: .
      dockerfile: ./src/Api/Holefeeder.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__BudgetingConnectionString: Server=mariadb;Port=3306;User Id=root;Password=${MARIADB_ROOT_PASSWORD};Database=budgeting_dev;
      Serilog__WriteTo__1__Args__apiKey: ${SEQ_API_KEY}

  web:
    image: holefeeder_web
    build:
      context: .
      dockerfile: ./src/Web/Holefeeder.Web/Dockerfile
    expose:
      - 80
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Serilog__WriteTo__1__Args__apiKey: ${SEQ_API_KEY}
