# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.8'

services:

  traefik:
    image: traefik:latest
    container_name: "traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "16379:6379"
      - "15432:5432"
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Map the certificats into the container
      - .docker/certs:/etc/certs:ro
    networks:
      - traefik-public
    environment:
      - TRAEFIK_API=true
      - TRAEFIK_API_INSECURE=true
      - TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE=true
      - TRAEFIK_LOG_LEVEL=DEBUG
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_HTTP_HTTP_REDIRECTIONS_ENTRYPOINT_TO=https
      - TRAEFIK_ENTRYPOINTS_HTTP_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME=https
      - TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS=:443
      - TRAEFIK_ENTRYPOINTS_SQL_ADDRESS=:3306
      - TRAEFIK_ENTRYPOINTS_WHOAMI_ADDRESS=:5011
      - TRAEFIK_ENTRYPOINTS_TRAEFIK_HTTP_TLS_DOMAINS_0_MAIN=localtest.me
      - TRAEFIK_ENTRYPOINTS_TRAEFIK_HTTP_TLS_DOMAINS_0_SANS=*.localtest.me
    labels:
      - "traefik.enable=true"
      # - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localtest.me`)"
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.tls=true"
      # - "traefik.http.routers.traefik.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.traefik.service=api@internal"
      # Global HTTP -> HTTPS
      # - "traefik.tls.certificates[0].certFile=/etc/certs/localtest.me+4.pem"
      # - "traefik.tls.certificates[0].keyFile=/etc/certs/localtest.me+4-key.pem"
      - "traefik.tls.stores.default.defaultCertificate.certfile=/etc/certs/localtest.me+4.pem"
      - "traefik.tls.stores.default.defaultCertificate.keyfile=/etc/certs/localtest.me+4-key.pem"

  holefeederapi:
    image: holefeederapi
    build:
      context: .
      dockerfile: src/Api/Holefeeder.Api/Dockerfile
    ports:
      - 5001:5001

volumes:
  traefik-certificates:
networks:
  traefik-public:
