services:
  reverse-proxy:
    volumes:
      # Map the certificats into the container
      - .docker/certs:/etc/certs:ro

  postgres:
    ports:
      - 5432:5432

  seq:
    environment:
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true

  api:
    build:
      context: .
      dockerfile: ./src/Holefeeder.Api/Dockerfile
      tags:
        - '${DOCKER_REGISTRY:-holefeeder}/holefeeder-api:${VERSION:-latest}'
    ports:
      - 5001:80

  web:
    build:
      context: .
      dockerfile: ./src/Holefeeder.Web/Dockerfile
      tags:
        - '${DOCKER_REGISTRY:-holefeeder}/holefeeder-web:${VERSION:-latest}'
