services:
  reverse-proxy:
    volumes:
      # Map the certificats into the container
      - .docker/certs:/etc/certs:ro

  postgres:
    ports:
      - 5432:5432

  api:
    build:
      context: .
      dockerfile: ./src/Holefeeder.Api/Dockerfile
      tags:
        - '${DOCKER_REGISTRY:-holefeeder}/holefeeder-api:${VERSION:-latest}'
    environment:
      FeatureManagement__temp-new-azure-b2c-config: true

  web:
    build:
      context: .
      dockerfile: ./src/Holefeeder.Web/Dockerfile
      tags:
        - '${DOCKER_REGISTRY:-holefeeder}/holefeeder-web:${VERSION:-latest}'
