packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  better-sqlite3: true
  browser-tabs-lock: true
  esbuild: true
  msgpackr-extract: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - react-native-mmkv
  - react-native-nitro-modules

onlyBuiltDependencies:
  - better-sqlite3
  - browser-tabs-lock
  - esbuild
  - msgpackr-extract
  - unrs-resolver

overrides:
  expo-constants: ~56.0.18

patchedDependencies:
  '@expo/dom-webview@55.0.6': patches/@expo__dom-webview@55.0.6.patch
