services:
  reverse-proxy:
    image: traefik:v3.7.10
    container_name: reverse-proxy
    profiles: ["local"]
    restart: unless-stopped
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Map the static configuration into the container
      - .docker/traefik/traefik.${ENV}.yml:/etc/traefik/traefik.yml:ro
      # Map the dynamic configuration into the container
      - .docker/traefik/dynamic.${ENV}.yml:/etc/traefik/dynamic.yml:ro
      - traefik_certs:/letsencrypt

  portainer:
    image: portainer/portainer-ce:2.44.0-alpine
    container_name: portainer
    profiles: ["local"]
    expose:
      - 9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  whoami:
    image: traefik/whoami:v1.12
    container_name: whoami
    profiles: ["local"]
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  powersync:
    image: journeyapps/powersync-service:1.23.3
    container_name: holefeeder_powersync
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - postgres
    expose:
      - 8080
      - 8081
    command: ["start", "-r", "unified"]
    environment:
      - POWERSYNC_CONFIG_PATH=/config/powersync.yaml
      # Source Database Connection
      - PS_DB_HOST=postgres
      - PS_DB_PORT=5432
      - PS_DB_NAME=${POSTGRES_APP_DB}
      - PS_DB_USER=${POSTGRES_APP_USER}
      - PS_DB_PASSWORD=${POSTGRES_APP_PASSWORD}

      # Storage Database Connection
      - PS_STORAGE_DB_HOST=postgres
      - PS_STORAGE_DB_PORT=5432
      - PS_STORAGE_DB_NAME=${POSTGRES_APP_DB}
      - PS_STORAGE_DB_USER=${POSTGRES_APP_USER}
      - PS_STORAGE_DB_PASSWORD=${POSTGRES_APP_PASSWORD}

      # Auth & Admin
      - PS_JWT_JWKS_URI=https://dev-vx1jio3owhaqdmqa.ca.auth0.com/.well-known/jwks.json
      - PS_JWT_AUDIENCE=https://holefeeder-api.drifterapps.app
      - PS_POWERSYNC_ADMIN_TOKEN=${POWERSYNC_ADMIN_TOKEN}
    volumes:
      - ./.docker/powersync:/config
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://localhost:8080/probes/liveness').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))",
        ]
      interval: 5s
      timeout: 1s
      retries: 15

  postgres:
    image: postgres:18
    container_name: holefeeder_postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
      - POSTGRES_APP_DB=${POSTGRES_APP_DB}
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql
      - .docker/scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    command: ["postgres", "-c", "wal_level=logical"]
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_APP_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-migrator:
    image: postgres:18
    container_name: holefeeder_db-migrator
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_DB=${POSTGRES_APP_DB}
    volumes:
      - .docker/scripts/migrator.sh:/migrator.sh
    command: ["bash", "/migrator.sh"]

  adminer:
    image: adminer:5.5.1
    container_name: adminer
    profiles: ["local"]
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - postgres
    expose:
      - 8080

  api:
    container_name: holefeeder_api
    restart: unless-stopped
    depends_on:
      - postgres
    expose:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV}
      - ASPNETCORE_URLS=http://+
      - ConnectionStrings__BudgetingConnectionString=Host=postgres;Port=5432;Username=${POSTGRES_APP_USER};Password=${POSTGRES_APP_PASSWORD};Database=${POSTGRES_APP_DB};

  web:
    container_name: holefeeder_web
    restart: unless-stopped
    depends_on:
      - api
    expose:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV}
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.SpaProxy
      - ASPNETCORE_URLS=http://+
      - AngularSettings__RedirectUrl=https://holefeeder.${DOMAIN}

networks:
  default:
    name: proxy

volumes:
  postgres-data:
  traefik_certs:
  portainer_data:
