allowBuilds:
  better-sqlite3: true
  browser-tabs-lock: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - react-native-mmkv
  - react-native-nitro-modules

nodeLinker: hoisted

onlyBuiltDependencies:
  - better-sqlite3
  - browser-tabs-lock
  - unrs-resolver
patchedDependencies:
  '@expo/dom-webview@55.0.3': patches/@expo__dom-webview@55.0.3.patch
