### GET get-account-types
GET {{holefeeder_gateway}}/api/v2/enumerations/get-account-types
Authorization: Bearer {{$auth.token("AUTH0_HOLEFEEDER")}}

<> 2025-12-23T093127.200.json
<> 2025-12-23T084459.200.json
<> 2025-12-23T084139.200.json
<> 2025-12-23T084011.200.json

###

### GET get-category-types
GET {{holefeeder_gateway}}/api/v2/enumerations/get-category-types
Authorization: Bearer {{$auth.token("AUTH0_HOLEFEEDER")}}

<> 2025-12-23T093127.200.json
<> 2025-12-23T084459.200.json
<> 2025-12-23T084139.200.json
<> 2025-12-23T084011.200.json

###

### GET get-date-interval-types
GET {{holefeeder_gateway}}/api/v2/enumerations/get-date-interval-types
Authorization: Bearer {{$auth.token("AUTH0_HOLEFEEDER")}}

<> 2025-12-23T093127.200.json
<> 2025-12-23T084459.200.json
<> 2025-12-23T084139.200.json
<> 2025-12-23T084011.200.json

###
