// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DrifterApps.Holefeeder.Common.Enums.AccountTypes.CREDITCARD.", Justification = "<Pending>", Scope = "member", Target = "~F:DrifterApps.Holefeeder.Common.Enums.AccountTypes.CREDITCARD")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DrifterApps.Holefeeder.Common.Enums.AccountTypes.CREDITLINE.", Justification = "<Pending>", Scope = "member", Target = "~F:DrifterApps.Holefeeder.Common.Enums.AccountTypes.CREDITLINE")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'T ArgumentHelper.ThrowIfDefault<T>(T arg, string argName)' passes a literal string as parameter 'message' of a call to 'ArgumentException.ArgumentException(string? message, string? paramName)'. Retrieve the following string(s) from a resource table instead: \"Value cannot match type default value.\".", Justification = "<Pending>", Scope = "member", Target = "~M:DrifterApps.Holefeeder.Common.Extensions.ArgumentHelper.ThrowIfDefault``1(``0,System.String)~``0")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'string ArgumentHelper.ThrowIfNullOrEmpty(string arg, string argName)' passes a literal string as parameter 'message' of a call to 'ArgumentException.ArgumentException(string? message, string? paramName)'. Retrieve the following string(s) from a resource table instead: \"Value cannot be empty.\".", Justification = "<Pending>", Scope = "member", Target = "~M:DrifterApps.Holefeeder.Common.Extensions.ArgumentHelper.ThrowIfNullOrEmpty(System.String,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'IEnumerable<TItem> ArgumentHelper.ThrowIfNullOrEmpty<TItem>(IEnumerable<TItem> arg, string argName)' passes a literal string as parameter 'message' of a call to 'ArgumentException.ArgumentException(string? message, string? paramName)'. Retrieve the following string(s) from a resource table instead: \"Value cannot be empty.\".", Justification = "<Pending>", Scope = "member", Target = "~M:DrifterApps.Holefeeder.Common.Extensions.ArgumentHelper.ThrowIfNullOrEmpty``1(System.Collections.Generic.IEnumerable{``0},System.String)~System.Collections.Generic.IEnumerable{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'void ArgumentHelper.ValidateParameterName(string parameterName)' passes a literal string as parameter 'message' of a call to 'ArgumentException.ArgumentException(string? message, string? paramName)'. Retrieve the following string(s) from a resource table instead: \"Value cannot be empty.\".", Justification = "<Pending>", Scope = "member", Target = "~M:DrifterApps.Holefeeder.Common.Extensions.ArgumentHelper.ValidateParameterName(System.String)")]